# Generated by Django 5.2.12 on 2026-03-29 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherInfo',
            fields=[
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='info', serialize=False, to='schedule.teacher')),
                ('bio', models.TextField(blank=True)),
                ('academic_degree', models.CharField(blank=True)),
                ('years_to_experience', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
