# Generated by Django 6.0.3 on 2026-03-31 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_teacherinfo_id_alter_teacher_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherinfo',
            name='id',
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course', to='schedule.teacher'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone_number',
            field=models.CharField(error_messages={'unique': 'This phone_number already been registered.'}, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='teacher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='info', serialize=False, to='schedule.teacher'),
        ),
    ]
