# Generated by Django 6.0.3 on 2026-04-01 08:45

import django.core.validators
import django.utils.timezone
import schedule.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_remove_teacherinfo_id_alter_course_teacher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='pass_date',
            field=models.DateField(default=django.utils.timezone.now, validators=[django.core.validators.MaxValueValidator(django.utils.timezone.now, message='Дата выдачи паспорта не может быть в будущем')]),
        ),
        migrations.AddField(
            model_name='student',
            name='pass_issued',
            field=models.CharField(max_length=100, null=True, validators=[schedule.models.validate_min_words]),
        ),
        migrations.AddField(
            model_name='student',
            name='pass_number',
            field=models.CharField(error_messages={'unique': 'This pass number already been registered.'}, max_length=6, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='pass_serial',
            field=models.CharField(error_messages={'unique': 'This pass serial already been registered.'}, max_length=4, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='registration_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='residential_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='pass_date',
            field=models.DateField(default=django.utils.timezone.now, validators=[django.core.validators.MaxValueValidator(django.utils.timezone.now, message='Дата выдачи паспорта не может быть в будущем')]),
        ),
        migrations.AddField(
            model_name='teacher',
            name='pass_issued',
            field=models.CharField(max_length=100, null=True, validators=[schedule.models.validate_min_words]),
        ),
        migrations.AddField(
            model_name='teacher',
            name='pass_number',
            field=models.CharField(error_messages={'unique': 'This pass number already been registered.'}, max_length=6, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='pass_serial',
            field=models.CharField(error_messages={'unique': 'This pass serial already been registered.'}, max_length=4, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='teacherinfo',
            name='date_of_employment',
            field=models.DateField(default=django.utils.timezone.now, validators=[django.core.validators.MaxValueValidator(django.utils.timezone.now, message='Дата приема не может быть в будущем')]),
        ),
        migrations.AddField(
            model_name='teacherinfo',
            name='education',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='teacherinfo',
            name='marital_status',
            field=models.TextField(blank=True, validators=[schedule.models.validate_min_words, schedule.models.validate_start_with_letter]),
        ),
        migrations.AddField(
            model_name='teacherinfo',
            name='registration_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='teacherinfo',
            name='residential_address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(validators=[schedule.models.validate_min_words]),
        ),
        migrations.AlterField(
            model_name='course',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, validators=[django.core.validators.MinValueValidator(django.utils.timezone.now, message='Дата начала курса не может быть в прошлом')]),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=100, validators=[schedule.models.validate_no_numbers, schedule.models.validate_start_with_letter]),
        ),
        migrations.AlterField(
            model_name='student',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=100, validators=[schedule.models.validate_no_numbers, schedule.models.validate_start_with_letter]),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=100, validators=[schedule.models.validate_no_numbers, schedule.models.validate_start_with_letter]),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(max_length=100, validators=[schedule.models.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='departament',
            field=models.CharField(max_length=100, validators=[schedule.models.validate_min_words, schedule.models.validate_start_with_letter]),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='first_name',
            field=models.CharField(max_length=100, validators=[schedule.models.validate_no_numbers, schedule.models.validate_start_with_letter]),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='last_name',
            field=models.CharField(max_length=100, validators=[schedule.models.validate_no_numbers, schedule.models.validate_start_with_letter]),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone_number',
            field=models.CharField(error_messages={'unique': 'This phone_number already been registered.'}, max_length=100, unique=True, validators=[schedule.models.validate_phone_number]),
        ),
    ]
