# Generated by Django 6.0.3 on 2026-04-01 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_student_pass_date_student_pass_issued_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='pass_number',
            field=models.CharField(error_messages={'unique': 'This pass number already been registered.'}, max_length=10, null=True, unique=True),
        ),
    ]
