# Generated by Django 6.0.3 on 2026-04-01 16:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_alter_student_pass_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='pass_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
