# Generated by Django 6.0.3 on 2026-04-01 17:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0009_alter_teacher_pass_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherinfo',
            name='date_of_employment',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
