# Generated by Django 6.0.3 on 2026-04-01 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0010_alter_teacherinfo_date_of_employment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='pass_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='date_of_employment',
            field=models.DateField(),
        ),
    ]
