# Generated by Django 6.0.3 on 2026-04-02 16:26

import schedule.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0011_alter_teacher_pass_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherinfo',
            name='marital_status',
            field=models.TextField(blank=True, validators=[schedule.models.validate_start_with_letter]),
        ),
    ]
