# Generated by Django 6.0.3 on 2026-04-02 17:16

import schedule.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0012_alter_teacherinfo_marital_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='birth_date',
            field=models.DateField(null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='first_name',
            field=models.CharField(max_length=100, validators=[schedule.models.validate_no_numbers, schedule.models.validate_start_with_letter], verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='last_name',
            field=models.CharField(max_length=100, validators=[schedule.models.validate_no_numbers, schedule.models.validate_start_with_letter], verbose_name='Фамилия'),
        ),
    ]
