# Generated by Django 6.0.3 on 2026-04-03 11:28

import django.core.validators
import django.utils.timezone
import schedule.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0013_alter_teacher_birth_date_alter_teacher_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='min_description',
            field=models.CharField(default=1, max_length=30, verbose_name='Краткое описание курса'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(validators=[schedule.models.validate_min_words], verbose_name='Подробное описание курса'),
        ),
        migrations.AlterField(
            model_name='course',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата окончания курса'),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, validators=[django.core.validators.MinValueValidator(django.utils.timezone.now, message='Дата начала курса не может быть в прошлом')], verbose_name='Дата начала курса'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=100, validators=[schedule.models.validate_no_numbers, schedule.models.validate_start_with_letter], verbose_name='Наименование курса'),
        ),
        migrations.AlterField(
            model_name='student',
            name='birth_date',
            field=models.DateField(null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=100, validators=[schedule.models.validate_no_numbers, schedule.models.validate_start_with_letter], verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=100, validators=[schedule.models.validate_no_numbers, schedule.models.validate_start_with_letter], verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='student',
            name='pass_date',
            field=models.DateField(default=django.utils.timezone.now, validators=[django.core.validators.MaxValueValidator(django.utils.timezone.now, message='Дата выдачи паспорта не может быть в будущем')], verbose_name='Дата выдачи паспорта'),
        ),
        migrations.AlterField(
            model_name='student',
            name='pass_issued',
            field=models.CharField(max_length=100, null=True, validators=[schedule.models.validate_min_words], verbose_name='Кем выдан паспорт?'),
        ),
        migrations.AlterField(
            model_name='student',
            name='pass_number',
            field=models.CharField(error_messages={'unique': 'This pass number already been registered.'}, max_length=10, null=True, unique=True, verbose_name='Номер паспорта'),
        ),
        migrations.AlterField(
            model_name='student',
            name='pass_serial',
            field=models.CharField(error_messages={'unique': 'This pass serial already been registered.'}, max_length=4, null=True, unique=True, verbose_name='Серия паспорта'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(max_length=100, validators=[schedule.models.validate_phone_number], verbose_name='Контактный номер телефона'),
        ),
        migrations.AlterField(
            model_name='student',
            name='registration_address',
            field=models.TextField(blank=True, null=True, verbose_name='Адрес регистрации'),
        ),
        migrations.AlterField(
            model_name='student',
            name='residential_address',
            field=models.TextField(blank=True, null=True, verbose_name='Адрес фактического проживания'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='departament',
            field=models.CharField(max_length=100, validators=[schedule.models.validate_min_words, schedule.models.validate_start_with_letter], verbose_name='Кафедра'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен?'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='pass_date',
            field=models.DateField(verbose_name='Дата выдачи паспорта'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='pass_issued',
            field=models.CharField(max_length=100, null=True, validators=[schedule.models.validate_min_words], verbose_name='Кем выдан паспорт?'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='pass_number',
            field=models.CharField(error_messages={'unique': 'This pass number already been registered.'}, max_length=6, null=True, unique=True, verbose_name='Номер паспорта'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='pass_serial',
            field=models.CharField(error_messages={'unique': 'This pass serial already been registered.'}, max_length=4, null=True, unique=True, verbose_name='Серия паспорта'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone_number',
            field=models.CharField(error_messages={'unique': 'This phone_number already been registered.'}, max_length=100, unique=True, validators=[schedule.models.validate_phone_number], verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='academic_degree',
            field=models.CharField(blank=True, verbose_name='Ученая степень'),
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='bio',
            field=models.TextField(blank=True, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='date_of_employment',
            field=models.DateField(verbose_name='Дата трудоустройства'),
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='education',
            field=models.TextField(blank=True, verbose_name='Образование'),
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='marital_status',
            field=models.TextField(blank=True, validators=[schedule.models.validate_start_with_letter], verbose_name='Семейное положение'),
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='registration_address',
            field=models.TextField(blank=True, verbose_name='Адрес регистрации'),
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='residential_address',
            field=models.TextField(blank=True, verbose_name='Адрес фактического проживания'),
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='years_to_experience',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Стаж работы (в годах)'),
        ),
    ]
