# Generated by Django 6.0.3 on 2026-04-03 11:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0014_course_min_description_alter_course_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата начала курса'),
        ),
    ]
