# Generated by Django 6.0.3 on 2026-04-03 12:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0015_alter_course_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='pass_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата выдачи паспорта'),
        ),
        migrations.AlterField(
            model_name='student',
            name='pass_number',
            field=models.CharField(error_messages={'unique': 'This pass number already been registered.'}, max_length=10, null=True, verbose_name='Номер паспорта'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='pass_number',
            field=models.CharField(error_messages={'unique': 'This pass number already been registered.'}, max_length=6, null=True, verbose_name='Номер паспорта'),
        ),
    ]
