# Generated by Django 6.0.3 on 2026-04-04 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0016_alter_student_pass_date_alter_student_pass_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherinfo',
            name='marital_status',
            field=models.TextField(blank=True, verbose_name='Семейное положение'),
        ),
    ]
